# Generated by Django 2.0.4 on 2018-04-27 12:49

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('photo', models.FileField(blank=True, null=True, upload_to=student.models.upload_location)),
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('dept', models.CharField(choices=[('CS', 'Computer Science And Engineering'), ('IT', 'Information Technology'), ('EEE', 'Electrical & Electronics Engineering'), ('EC', 'Electronics & Communication'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], max_length=70)),
                ('dob', models.DateField()),
                ('desig', models.CharField(choices=[('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], default='Prof', max_length=20)),
                ('permaddr', models.TextField(max_length=50)),
                ('tempaddr', models.TextField(max_length=50)),
                ('category', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], default='Temporary', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('datejoin', models.DateField()),
                ('dateresig', models.DateField()),
                ('accessLv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FacultySubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(choices=[('1', 'S1'), ('2', 'S2'), ('3', 'S3'), ('4', 'S4'), ('5', 'S5'), ('6', 'S6'), ('7', 'S7'), ('8', 'S8')], default='A', max_length=2)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science And Engineering'), ('IT', 'Information Technology'), ('EEE', 'Electrical & Electronics Engineering'), ('EC', 'Electronics & Communication Engineering'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], default='A', max_length=50)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('year', models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048), (2049, 2049)])),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('photo', models.FileField(blank=True, null=True, upload_to=student.models.upload_location)),
                ('regno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science And Engineering'), ('IT', 'Information Technology'), ('EEE', 'Electrical & Electronics Engineering'), ('EC', 'Electronics & Communication'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], max_length=15)),
                ('cursem', models.CharField(choices=[('1', 'S1'), ('2', 'S2'), ('3', 'S3'), ('4', 'S4'), ('5', 'S5'), ('6', 'S6'), ('7', 'S7'), ('8', 'S8')], max_length=2)),
                ('join', models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048), (2049, 2049)])),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('status', models.CharField(choices=[('Active', 'Currently Studying'), ('Pass out', 'Course Completed'), ('Drop out', 'Drop out ')], default='Active', max_length=20)),
                ('parent', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('regno',),
            },
        ),
        migrations.CreateModel(
            name='Subject_Profile',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science And Engineering'), ('IT', 'Information Technology'), ('EEE', 'Electrical & Electronics Engineering'), ('EC', 'Electronics & Communication'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], max_length=70)),
                ('sem', models.CharField(choices=[('1', 'S1'), ('2', 'S2'), ('3', 'S3'), ('4', 'S4'), ('5', 'S5'), ('6', 'S6'), ('7', 'S7'), ('8', 'S8')], max_length=2)),
                ('stype', models.CharField(choices=[('T', 'Theory'), ('L', 'Practical'), ('P', 'Project')], max_length=15)),
                ('credit', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ('sem',),
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048), (2049, 2049)])),
                ('dept', models.CharField(choices=[('CS', 'Computer Science And Engineering'), ('IT', 'Information Technology'), ('EEE', 'Electrical & Electronics Engineering'), ('EC', 'Electronics & Communication Engineering'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], max_length=60)),
                ('theory_no', models.PositiveIntegerField()),
                ('max_internal', models.PositiveIntegerField()),
                ('max_external', models.PositiveIntegerField()),
                ('lab_no', models.PositiveIntegerField()),
                ('max_lab_external', models.PositiveIntegerField()),
                ('max_miniproj', models.PositiveIntegerField()),
                ('max_mainproj', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marklist',
            fields=[
                ('regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.Student')),
                ('branch', models.CharField(choices=[('CS', 'Computer Science And Engineering'), ('IT', 'Information Technology'), ('EEE', 'Electrical & Electronics Engineering'), ('EC', 'Electronics & Communication'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], max_length=70)),
                ('cursem', models.CharField(choices=[('1', 'S1'), ('2', 'S2'), ('3', 'S3'), ('4', 'S4'), ('5', 'S5'), ('6', 'S6'), ('7', 'S7'), ('8', 'S8')], max_length=2)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('sub1', models.CharField(default='0', max_length=60)),
                ('mark1', models.SmallIntegerField(default='0')),
                ('sub2', models.CharField(default='0', max_length=60)),
                ('mark2', models.SmallIntegerField(default='0')),
                ('sub3', models.CharField(default='0', max_length=60)),
                ('mark3', models.SmallIntegerField(default='0')),
                ('sub4', models.CharField(default='0', max_length=60)),
                ('mark4', models.SmallIntegerField(default='0')),
                ('sub5', models.CharField(default='0', max_length=60)),
                ('mark5', models.SmallIntegerField(default='0')),
                ('sub6', models.CharField(default='0', max_length=60)),
                ('mark6', models.SmallIntegerField(blank=True, default='0')),
                ('subl1', models.CharField(default='0', max_length=60)),
                ('markl1', models.SmallIntegerField(default='0')),
                ('subl2', models.CharField(default='0', max_length=60)),
                ('markl2', models.SmallIntegerField(default='0')),
                ('subl3', models.CharField(blank=True, max_length=60, null=True)),
                ('markl3', models.SmallIntegerField(blank=True, default='0')),
                ('subl4', models.CharField(blank=True, max_length=60, null=True)),
                ('markl4', models.SmallIntegerField(blank=True, default='0')),
            ],
        ),
        migrations.AddField(
            model_name='subject_profile',
            name='syllabussubid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='student.Syllabus'),
        ),
        migrations.AddField(
            model_name='facultysubject',
            name='subcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Subject_Profile'),
        ),
    ]
