# Generated by Django 2.0.4 on 2018-04-28 15:38

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20180428_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marklist',
            name='regno',
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=student.models.upload_location),
        ),
        migrations.DeleteModel(
            name='Marklist',
        ),
    ]
