# Generated by Django 2.0.4 on 2018-04-28 15:39

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20180428_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CS', 'Computer Science And Engineering'), ('IT', 'Information Technology'), ('EEE', 'Electrical & Electronics Engineering'), ('EC', 'Electronics & Communication'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], max_length=70)),
                ('cursem', models.CharField(choices=[('1', 'S1'), ('2', 'S2'), ('3', 'S3'), ('4', 'S4'), ('5', 'S5'), ('6', 'S6'), ('7', 'S7'), ('8', 'S8')], max_length=2)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('sub1', models.CharField(default='0', max_length=60)),
                ('mark1', models.SmallIntegerField(default='0')),
                ('sub2', models.CharField(default='0', max_length=60)),
                ('mark2', models.SmallIntegerField(default='0')),
                ('sub3', models.CharField(default='0', max_length=60)),
                ('mark3', models.SmallIntegerField(default='0')),
                ('sub4', models.CharField(default='0', max_length=60)),
                ('mark4', models.SmallIntegerField(default='0')),
                ('sub5', models.CharField(default='0', max_length=60)),
                ('mark5', models.SmallIntegerField(default='0')),
                ('sub6', models.CharField(default='0', max_length=60)),
                ('mark6', models.SmallIntegerField(blank=True, default='0')),
                ('subl1', models.CharField(default='0', max_length=60)),
                ('markl1', models.SmallIntegerField(default='0')),
                ('subl2', models.CharField(default='0', max_length=60)),
                ('markl2', models.SmallIntegerField(default='0')),
                ('subl3', models.CharField(blank=True, max_length=60, null=True)),
                ('markl3', models.SmallIntegerField(blank=True, default='0')),
                ('subl4', models.CharField(blank=True, max_length=60, null=True)),
                ('markl4', models.SmallIntegerField(blank=True, default='0')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=student.models.upload_location),
        ),
        migrations.AddField(
            model_name='marklist',
            name='regno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
