# Generated by Django 2.0.4 on 2018-04-28 15:47

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20180428_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marklist',
            options={'ordering': ('cursem',)},
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=student.models.upload_location),
        ),
    ]
