# Generated by Django 2.0.4 on 2018-04-30 09:48

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20180428_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='marklist',
            name='type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=student.models.upload_location),
        ),
    ]
