# Generated by Django 2.0.4 on 2019-05-04 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 11, 13, 15, 901648, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 11, 13, 15, 896110, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='rollnoregnomap',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 11, 13, 15, 902254, tzinfo=utc)),
        ),
    ]
