# Generated by Django 2.0.4 on 2019-05-17 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20190508_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 9, 6, 35, 564323, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='rollnoregnomap',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 9, 6, 35, 569619, tzinfo=utc)),
        ),
    ]
